
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIFFleftIFleftORleftANDrightNOTAND CONST_CERO CONST_UNO IF IFF NOT OR PAREN_D PAREN_I VARIABLESformula : formula AND formula\n               | formula OR formula\n               | formula IF formula\n               | formula IFF formulaformula : NOT formulaformula : PAREN_I formula PAREN_Dformula : CONST_CERO\n               | CONST_UNOformula : VARIABLES'
    
_lr_action_items = {'NOT':([0,2,3,7,8,9,10,],[2,2,2,2,2,2,2,]),'PAREN_I':([0,2,3,7,8,9,10,],[3,3,3,3,3,3,3,]),'CONST_CERO':([0,2,3,7,8,9,10,],[4,4,4,4,4,4,4,]),'CONST_UNO':([0,2,3,7,8,9,10,],[5,5,5,5,5,5,5,]),'VARIABLES':([0,2,3,7,8,9,10,],[6,6,6,6,6,6,6,]),'$end':([1,4,5,6,11,13,14,15,16,17,],[0,-7,-8,-9,-5,-1,-2,-3,-4,-6,]),'AND':([1,4,5,6,11,12,13,14,15,16,17,],[7,-7,-8,-9,-5,7,-1,7,7,7,-6,]),'OR':([1,4,5,6,11,12,13,14,15,16,17,],[8,-7,-8,-9,-5,8,-1,-2,8,8,-6,]),'IF':([1,4,5,6,11,12,13,14,15,16,17,],[9,-7,-8,-9,-5,9,-1,-2,-3,9,-6,]),'IFF':([1,4,5,6,11,12,13,14,15,16,17,],[10,-7,-8,-9,-5,10,-1,-2,-3,-4,-6,]),'PAREN_D':([4,5,6,11,12,13,14,15,16,17,],[-7,-8,-9,-5,17,-1,-2,-3,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,2,3,7,8,9,10,],[1,11,12,13,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> formula AND formula','formula',3,'p_formula_binaria','analizador.py',53),
  ('formula -> formula OR formula','formula',3,'p_formula_binaria','analizador.py',54),
  ('formula -> formula IF formula','formula',3,'p_formula_binaria','analizador.py',55),
  ('formula -> formula IFF formula','formula',3,'p_formula_binaria','analizador.py',56),
  ('formula -> NOT formula','formula',2,'p_formula_unaria','analizador.py',60),
  ('formula -> PAREN_I formula PAREN_D','formula',3,'p_formula_parens','analizador.py',64),
  ('formula -> CONST_CERO','formula',1,'p_formula_constante','analizador.py',68),
  ('formula -> CONST_UNO','formula',1,'p_formula_constante','analizador.py',69),
  ('formula -> VARIABLES','formula',1,'p_formula_variable','analizador.py',73),
]
